In [1]:
import numpy as np
import pandas as pd

In [7]:
import chardet
with open("C:\\Users\\Admin\\Downloads\\email\\SMS_train.csv","rb") as f:
    raw_data=f.read(10000)
result=chardet.detect(raw_data)
print(result)

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}

In [11]:
df = pd.read_csv("C:\\Users\\Admin\\Downloads\\email\\SMS_train.csv",encoding='windows-1252')

In [15]:
df.head(10)

   S. No.                                       Message_body     Label
0       1                         Rofl. Its true to its name  Non-Spam
1       2  The guy did some bitching but I acted like i'd...  Non-Spam
2       3  Pity, * was in mood for that. So...any other s...  Non-Spam
3       4               Will ü b going to esplanade fr home?  Non-Spam
4       5  This is the 2nd time we have tried 2 contact u...      Spam
5       6  REMINDER FROM O2: To get 2.50 pounds free call...      Spam
6       7                                       Huh y lei...  Non-Spam
7       8  Why don't you wait 'til at least wednesday to ...  Non-Spam
8       9                                Ard 6 like dat lor.  Non-Spam
9      10  Ok lor... Sony ericsson salesman... I ask shuh...  Non-Spam

In [20]:
df['Label'].value_counts()

Label
Non-Spam    835
Spam        122
Name: count, dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df['Message_body'] =df['Message_body'].str.lower()

In [24]:
df.head()

   S. No.                                       Message_body     Label
0       1                         rofl. its true to its name  Non-Spam
1       2  the guy did some bitching but i acted like i'd...  Non-Spam
2       3  pity, * was in mood for that. so...any other s...  Non-Spam
3       4               will ü b going to esplanade fr home?  Non-Spam
4       5  this is the 2nd time we have tried 2 contact u...      Spam

In [50]:
X = df['Message_body']
y = df['Label']

In [51]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [52]:
y[0:10]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [53]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [54]:
X_train

414                      like  &lt;#&gt; , same question
725    hmmm.... mayb can try e shoppin area one, but ...
223    my parents, my kidz, my friends n my colleague...
757    don't worry though, i understand how important...
946                          this is a long fuckin showr
                             ...
767      i dont know why she.s not getting your messages
72                    why did i wake up on my own &gt;:(
908    this message is from a great doctor in india:-...
235    garbage bags, eggs, jam, bread, hannaford whea...
37     hey chief, can you give me a bell when you get...
Name: Message_body, Length: 765, dtype: object

In [55]:

# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
cv = CountVectorizer()

In [59]:
X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

In [60]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [61]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.9270833333333334

In [62]:

confusion_matrix(y_test,y_pred)

array([[160,   8],
       [  6,  18]])

In [63]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.9322916666666666

In [65]:

cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.9322916666666666

In [68]:

cv = CountVectorizer(max_features=6000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.9375

In [99]:
new_msg = ["Hey, are we still meeting tomorrow?".lower()]

In [95]:
new_msg = ["UpgrdCentre Orange customer, you may now claim your FREE CAMERA PHONE upgrade for your loyalty. Call now on 0207 153 9153. Offer ends 26th July. T&C's apply. Opt-out available"]

In [100]:
new_msg_bow = cv.transform(new_msg).toarray()

In [101]:
prediction = gnb.predict(new_msg_bow)
print(prediction)

[0]