In [1]:
import numpy as np
import pandas as pd

In [2]:
import chardet
with open("C:\\Users\\Admin\\Downloads\\archive (1)\\SMS_train.csv","rb") as f:
    raw_data=f.read(10000)
result=chardet.detect(raw_data)
print(result)

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}

In [3]:
nlp=pd.read_csv("C:\\Users\\Admin\\Downloads\\archive (1)\\SMS_train.csv",encoding='Windows-1252')

In [4]:
nlp.head(5)

   S. No.                                       Message_body     Label
0       1                         Rofl. Its true to its name  Non-Spam
1       2  The guy did some bitching but I acted like i'd...  Non-Spam
2       3  Pity, * was in mood for that. So...any other s...  Non-Spam
3       4               Will ü b going to esplanade fr home?  Non-Spam
4       5  This is the 2nd time we have tried 2 contact u...      Spam

# Dealing with html tags

In [5]:
import re 
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [22]:
text='<p>Hi hello</p> <h1>single seena </h1>'

In [23]:
remove_html_tags(text)

'Hi hello single seena '

In [24]:
text.lower()

'<p>hi hello</p> <h1>single seena </h1>'

# to lower case

In [29]:
nlp['Message_body'].str.lower()

0                             rofl. its true to its name
1      the guy did some bitching but i acted like i'd...
2      pity, * was in mood for that. so...any other s...
3                   will ü b going to esplanade fr home?
4      this is the 2nd time we have tried 2 contact u...
                             ...
952    hows my favourite person today? r u workin har...
953                        how much you got for cleaning
954    sorry da. i gone mad so many pending works wha...
955                                   wat time ü finish?
956                      just glad to be talking to you.
Name: Message_body, Length: 957, dtype: object

# Removing url in the text

In [40]:
def remove_url(text):
    pattern=re.compile('https?://\S+|WWW\.\S+')
    return pattern.sub(r'',text)

In [45]:
text='https://www.hackerrank.com/profile/srinivasdr25 hi hello single seena'

In [46]:
remove_url(text)

' hi hello single seena'

In [47]:
nlp.head()

   S. No.                                       Message_body     Label
0       1                         Rofl. Its true to its name  Non-Spam
1       2  The guy did some bitching but I acted like i'd...  Non-Spam
2       3  Pity, * was in mood for that. So...any other s...  Non-Spam
3       4               Will ü b going to esplanade fr home?  Non-Spam
4       5  This is the 2nd time we have tried 2 contact u...      Spam

In [48]:
nlp['Message_body'] = nlp['Message_body'].apply(remove_url)

# Removing punctuations